# Generated by Django 4.0 on 2022-01-23 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='user_id',
            new_name='user',
        ),
    ]
